# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoDoc < Formula
  desc "Generate markdown tables for your Github action and reusable workflow with ease."
  homepage "https://github.com/tj-actions/auto-doc"
  version "2.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tj-actions/auto-doc/releases/download/v2.2.5/auto-doc_2.2.5_Darwin_x86_64.tar.gz"
      sha256 "4a4113d266309d3d250b4c99e7899689d829840d77371bb37756822f84d25efd"

      def install
        bin.install "auto-doc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tj-actions/auto-doc/releases/download/v2.2.5/auto-doc_2.2.5_Darwin_arm64.tar.gz"
      sha256 "988c30ef053eccd598aa3b629ee1090b2a5b526017f97f95ebc08655426071e6"

      def install
        bin.install "auto-doc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tj-actions/auto-doc/releases/download/v2.2.5/auto-doc_2.2.5_Linux_arm64.tar.gz"
      sha256 "05ade40e47f9db2939f19255942338b8fd77190aac7463ccb8eb9c1052fb40b4"

      def install
        bin.install "auto-doc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tj-actions/auto-doc/releases/download/v2.2.5/auto-doc_2.2.5_Linux_armv6.tar.gz"
      sha256 "e2441bc7826c90ff039e9adda456329b129ece40e2e024495370c25bcb1defcd"

      def install
        bin.install "auto-doc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tj-actions/auto-doc/releases/download/v2.2.5/auto-doc_2.2.5_Linux_x86_64.tar.gz"
      sha256 "26cfd2106b39bff5b11e5a9864226ec3d575832c8efacf21f5b5bef9a22cf8d2"

      def install
        bin.install "auto-doc"
      end
    end
  end
end
